version: '3.2'

services:

 freeradius:
  image: "freeradius/freeradius-server"
  restart: always
  ports:
   - "1812:1812/udp"
   - "1813:1813"
  volumes:
   - "./clients.conf:/etc/freeradius/clients.conf"
   - "./users:/etc/freeradius/users"
   - "./log:/var/log/freeradius"
   - "./radiusd.conf:/etc/freeradius/radiusd.conf"
